site_name: IMDEO

theme:
  name: mkdocs

extra_css:
  - stylesheets/extra.css

nav:
  - Accueil: index.md
  - Linux:
      - GRUB: Linux/grub.md
      - LVM: Linux/lvm.md
  - Système:
      - Sécuriser GRUB: Linux/secugrub.md
      - LVM Resize: Système/resize.md
      - SSH: Système/ssh.md